bindings:
  a: 0.0
  b: 0.0
  c: 0.0
  chart_type: line
  danger_threshold: 85.0
  device_id: temp_line
  device_type: env_sensor
  display_name: Temperature
  firmware_version: 1.0.0
  is_blinkable: false
  is_connected: true
  max_value: 100.0
  unit_of_measure_label: Â°F
  warn_threshold: 69.0
bus_topic: a01
module_type: monitoring
name: Temp
template: chart_card
