bindings:
  a: 0.0
  b: 0.0
  c: 0.0
  chart_type: sparkline
  danger_threshold: 80.0
  device_id: w01
  device_type: water_sensor
  display_name: Water Level
  firmware_version: 1.0.0
  is_blinkable: false
  is_connected: true
  max_value: 100.0
  unit_of_measure_label: cm
  warn_threshold: 50.0
bus_topic: a01
module_type: monitoring
name: Water Level
template: chart_card
