bindings:
  description: Emergency survival procedures and protocols
  last_updated: 2024-01-15
  version: '2.1'
bus_topic: knowledge_survival
module_type: knowledge
name: Survival Guide
template: ''
